name: Install Dependencies

runs:
  using: composite
  steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        echo "Install Linux dependencies"
        sudo apt-get update
        sudo apt-get install -y cmake
        sudo apt-get install -y libgmp-dev
        sudo apt-get install -y python3-pip
        python3 -m pip install sympy
        echo "Install Linux dependencies [DONE]"

    - name: Install Mac Dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: |
        echo "Install Mac dependencies"
        brew update || true
        ## gmp and python are already installed in the latest macOS
        # brew install gmp
        # brew install python
        ## Try to install sympy, but don't fail if it doesn't work (it's optional)
        ## sympy is optional - tests will work without it
        ## Use --break-system-packages with --user as recommended by PEP 668
        set +e  # Don't exit on error
        if command -v pip3 &> /dev/null; then
          pip3 install --user --break-system-packages sympy || echo "Warning: Failed to install sympy with pip3, continuing anyway"
        elif python3 -m pip --version &> /dev/null; then
          python3 -m pip install --user --break-system-packages sympy || echo "Warning: Failed to install sympy with python3 -m pip, continuing anyway"
        else
          python3 -m ensurepip --upgrade || python3 -m ensurepip || true
          python3 -m pip install --user --break-system-packages sympy || echo "Warning: Failed to install sympy, continuing anyway"
        fi
        set -e  # Re-enable exit on error
        echo "Install Mac dependencies [DONE]"
