language: c

notifications:
  slack: sriformalmethods:1DWq3BI30wLc3ZAc3Fc37n6x

dist:
  # Ubuntu 18.04 LTS
  - bionic

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
      - make
      - mingw-w64
  homebrew:
    packages:
      - cmake
      - gmp
      - pyenv
      - mingw-w64
    update: true

env:
  matrix:
    # iam: the precise versions are need, so we know whether we have to install
    # or just choose. I picked these, because only 2.7.15 and 3.6.7 needs to be built (on osx).
    # the linux image has these versions already.
    - CMAKE_BUILD_TYPE=Debug PYTHON=2.7.15
    - CMAKE_BUILD_TYPE=Debug PYTHON=3.6.7
    - CMAKE_BUILD_TYPE=Release PYTHON=2.7.15
    - CMAKE_BUILD_TYPE=Release PYTHON=3.6.7
    - CMAKE_BUILD_TYPE=Release CROSS_COMPILE=On CMAKE_ADDITIONAL_OPTIONS="-DCMAKE_TOOLCHAIN_FILE=../scripts/toolchain-mingw64-cross-compile.cmake -DLIBPOLY_BUILD_PYTHON_API=Off -DLIBPOLY_BUILD_CPP_API=Off"

install:
   - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/ubuntu.deps.sh; fi
   - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/osx.deps.sh; fi
   - if [ "$CROSS_COMPILE" = "On" ]; then ./scripts/mingw32.deps.sh; fi

script:
  # iam: need to make sure the shims intercept (osx is the culprit here)
  - source ${HOME}/.bash_profile;
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_INSTALL_PREFIX=$HOME/prefix ..
  - make
  - make check
  - make test
  - make install
